### ISSUE TITLE
Create a app.swift File

### ISSUE THREAD

**Issue by hanut** [hanut/gullu-bomb#1]
Write a tiny app.swift file with some random code in it. 
Code should - 

- [x] Print a line

- [x] Create a variable

- [x] Update the variable

**Comment by GurleenDigital** [comment]
apples-MacBook-Pro-2:gullu-bomb Gurleen$ git pull --rebase origin master
fatal: unable to access 'https://github.com/hanut/gullu-bomb.git/': getpeername() failed with errno 22: Invalid argument
