### ISSUE TITLE
Create a test.swift file

### ISSUE THREAD

**Issue by hanut** [hanut/gullu-bomb#2]
Create a test.swift file that prints 'test'

**Comment by GurleenDigital** [comment]
apples-MacBook-Pro-2:gullu-bomb Gurleen$ git status
On branch issue#2
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    File.swift

no changes added to commit (use "git add" and/or "git commit -a")
apples-MacBook-Pro-2:gullu-bomb Gurleen$
